### PR TITLE
Problem: Nitro build fails with upgrade of zeroize 1.4.0(#129)

### PR DESCRIPTION
**Pull request by linfeng-crypto**
zeroize 1.4.1 requires Rust 1.51 or newer.

### CODE REVIEW

**Review by tomtau — CHANGES_REQUESTED** [review]
it'll be good to upgrade the versions of zeroize and secrecy if possible?

**Comment by tomtau** [comment]
all CI pipelines seem to fail: https://github.com/crypto-com/tmkms-light/pull/138/checks?check_run_id=3189601466#step:4:13

**Comment by tomtau** [comment]
(due to this PR https://github.com/crypto-com/tmkms-light/pull/132 )

**Comment by linfeng-crypto** [comment]
https://github.com/RustCrypto/AEADs/pull/349

**Comment by tomtau** [comment]
maybe revert this commit https://github.com/crypto-com/tmkms-light/pull/132/commits/77c4ced8581d25ad506805b605f4e0202f87d4f7 and pin to 1.3 for now?

**Comment by linfeng-crypto** [comment]
> maybe we can revert this commit [77c4ced](https://github.com/crypto-com/tmkms-light/commit/77c4ced8581d25ad506805b605f4e0202f87d4f7) and pin to 1.3 for now?

I'll revert in issue #137

**Comment by linfeng-crypto** [comment]
> maybe we can revert this commit [77c4ced](https://github.com/crypto-com/tmkms-light/commit/77c4ced8581d25ad506805b605f4e0202f87d4f7) and pin to 1.3 for now?

yes, need to create a new issue.

**Comment by tomtau** [comment]
shall we close this PR given it won't be possible to upgrade to 1.4?

**Comment by linfeng-crypto** [comment]
> shall we close this PR given it won't be possible to upgrade to 1.4?

yes, and also need to set the the version `=1.3.0`

**Pull request closed without merging**
